In [2]:
import numpy as np
import pandas as pd

# Groupby in Pandas

Groupby in Pandas is a powerful tool that allows you to group data based on one or more columns and perform aggregate functions on those groups.

In [6]:
tip = pd.read_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/tip.csv')
titanic = pd.read_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/Titanic-Dataset.csv')
planets = pd.read_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/planets.csv')
bookings = pd.read_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/bookings.csv')
mpg = pd.read_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/mpg.csv')

In [ ]:
tip.groupby("day")["total_bill"].size()

day
Fri     19
Sat     87
Sun     76
Thur    62
Name: total_bill, dtype: int64

In [8]:
tip.groupby("day")["total_bill"].mean()

day
Fri     17.151579
Sat     20.441379
Sun     21.410000
Thur    17.682742
Name: total_bill, dtype: float64

In [9]:
tip.groupby("day")["total_bill"].mean()*100

day
Fri     1715.157895
Sat     2044.137931
Sun     2141.000000
Thur    1768.274194
Name: total_bill, dtype: float64

Aggregate functions are functions that take a list of values and return a single value. For example, the mean function takes a list of numbers and returns their average. In pandas, you can use aggregate functions to summarize data in a DataFrame.

In [ ]:
tip.groupby("day").agg(
    bill_count = ("total_bill", "size"),
    bill_mean = ("total_bill", "mean"),
    avg_tip = ("tip", "mean")
)

      bill_count  bill_mean   avg_tip
day
Fri           19  17.151579  2.734737
Sat           87  20.441379  2.993103
Sun           76  21.410000  3.255132
Thur          62  17.682742  2.771452

In [ ]:
tip.groupby("time")["total_bill"].size()

time
Dinner    176
Lunch      68
Name: total_bill, dtype: int64

In [ ]:
# Summary is a way of aggregating data based on a specific column, in this case, "day". The aggregation functions used here are:
# - "size": counts the number of rows in each group
# - "mean": calculates the average of the values in each group

summary = tip.groupby("day").agg(
    bill_count = ("total_bill", "size"),
    bill_mean = ("total_bill", "mean"),
    avg_tip = ("tip", "mean")
).round(2)

summary

      bill_count  bill_mean  avg_tip
day
Fri           19      17.15     2.73
Sat           87      20.44     2.99
Sun           76      21.41     3.26
Thur          62      17.68     2.77

In [ ]:
# To convert the summary DataFrame to a CSV file, we can use the `to_csv()` method.

summary.to_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/tip_summary.csv')

In [22]:
summary.columns
summary.index

Index(['Fri', 'Sat', 'Sun', 'Thur'], dtype='str', name='day')

In [23]:
tip.groupby("time")["total_bill"].size()

time
Dinner    176
Lunch      68
Name: total_bill, dtype: int64

In [24]:
flat = summary.reset_index()
print(flat.columns.tolist())
flat.head()

['day', 'bill_count', 'bill_mean', 'avg_tip']

    day  bill_count  bill_mean  avg_tip
0   Fri          19      17.15     2.73
1   Sat          87      20.44     2.99
2   Sun          76      21.41     3.26
3  Thur          62      17.68     2.77

In [25]:
summary

      bill_count  bill_mean  avg_tip
day
Fri           19      17.15     2.73
Sat           87      20.44     2.99
Sun           76      21.41     3.26
Thur          62      17.68     2.77

In [26]:
summary.to_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/tip_summary.csv', index=False)
flat = pd.read_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/tip_summary.csv')
flat.head()

   bill_count  bill_mean  avg_tip
0          19      17.15     2.73
1          87      20.44     2.99
2          76      21.41     3.26
3          62      17.68     2.77

In [34]:
smoker_report = tip.groupby("smoker").agg(
    bill_count = ("total_bill", "size"),
    avg_bill = ("total_bill", "mean"),
    avg_tip = ("tip", "mean")
)

smoker_report.reset_index().to_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/smoker_report.csv')
temp = pd.read_csv('/Users/aareev/VS-Code/Vedam/Vedam Semester 3/Python(ML) Sem 3/Data/smoker_report.csv')
temp.head()

   Unnamed: 0 smoker  bill_count   avg_bill   avg_tip
0           0     No         151  19.188278  2.991854
1           1    Yes          93  20.756344  3.008710

In [ ]:
# idxmax() - returns the index label of row holding the maximum - not the value, the address

In [35]:
print(bookings["customer"].str.lower().str.strip())

0     ravi sharma
1      priya iyer
2     ravi sharma
3      amit kumar
4     priya  iyer
5     ravi sharma
6       sana khan
7      amit kumar
8      vikram rao
9      sana  khan
10     priya iyer
11     vikram rao
Name: customer, dtype: str